### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by miampf** [190n/plymouth-blahaj#1]
Hey there,
I love the theme that you put together and have been using it for a while! I wanted to package it for the [nix package registry](https://github.com/NixOS/nixpkgs/tree/master) so that other people can use the theme more easily on NixOS. Since you have no license like MIT provided I would have to mark this package as unfree (since, by default, the rights to everything is "All rights reserved") which would make installation a bit more difficult because nix prevents the installation of unfree packages by default. Would you mind adding an open source license to your project? This would also allow others to (legally) make potential changes to your work on their own and republish their new versions. If you want to have a look on all possible licenses you can look [here](https://opensource.org/licenses) and you can use [this website](https://choosealicense.com/) to figure out what you want to use. Obviously, if you don't want to add a software license, that's completely fair as well.
Thanks in advance :3

**Comment by 190n** [comment]
Done :3

Let me know if there are any other issues with this I can fix, I distro hopped and never actually set it back up on Fedora so there might be stuff that's broken in the last 2 years. Glad you're enjoying the theme.
